In [85]:
import pandas as pd

In [86]:
df1 = pd.read_csv('IDEFC_NM_sep24.csv', encoding='ISO-8859-1')

In [87]:
df1

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2,1,2,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0,1,0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0,1,2,0.0,0.0,0.0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2,0,0,1,0,0,0,0,0,0.0,0.0,0.0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31355,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Falsificación,Falsificación,Falsificación,3,9,17,14,8,8,9,9,10,NaN,NaN,NaN
31356,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Contra el medio ambiente,Contra el medio ambiente,Contra el medio ambiente,0,0,0,0,0,0,2,0,0,NaN,NaN,NaN
31357,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,21,22,34,35,34,37,29,25,21,NaN,NaN,NaN
31358,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales,0,1,0,11,31,23,0,0,0,NaN,NaN,NaN
31359,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Otros delitos del Fuero Común,Otros delitos del Fuero Común,Otros delitos del Fuero Común,151,184,173,199,208,179,189,154,148,NaN,NaN,NaN

In [88]:
df2 = pd.read_csv('IDEFC_ago2024.csv', encoding='ISO-8859-1')

In [89]:
df2 = df2[df2['AÑO'] < 2015]
df2

,AÑO,INEGI,ENTIDAD,MODALIDAD,TIPO,SUBTIPO,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
0,1997,1,AGUASCALIENTES,DELITOS PATRIMONIALES,ABUSO DE CONFIANZA,ABUSO DE CONFIANZA,17,17,17,17,17,17,32,0,38,28,22,31
1,1997,1,AGUASCALIENTES,DELITOS PATRIMONIALES,DAÑO EN PROPIEDAD AJENA,DAÑO EN PROPIEDAD AJENA,45,45,45,45,45,45,108,40,117,38,73,133
2,1997,1,AGUASCALIENTES,DELITOS PATRIMONIALES,EXTORSION,EXTORSION,0,0,0,0,0,0,0,0,0,0,0,0
3,1997,1,AGUASCALIENTES,DELITOS PATRIMONIALES,FRAUDE,FRAUDE,9,9,9,9,9,9,52,0,55,51,42,44
4,1997,1,AGUASCALIENTES,DELITOS PATRIMONIALES,DESPOJO,CON VIOLENCIA,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38011,2014,32,ZACATECAS,DELITOS SEXUALES (VIOLACION),VIOLACION,VIOLACION,6,7,10,20,10,15,10,17,13,11,9,13
38012,2014,32,ZACATECAS,OTROS DELITOS,AMENAZAS,AMENAZAS,14,24,26,27,28,49,41,32,20,35,21,22
38013,2014,32,ZACATECAS,OTROS DELITOS,ESTUPRO,ESTUPRO,1,6,2,2,0,2,1,0,3,1,5,2
38014,2014,32,ZACATECAS,OTROS DELITOS,OTROS SEXUALES,OTROS SEXUALES,1,1,2,1,1,2,1,2,2,5,3,1
38015,2014,32,ZACATECAS,OTROS DELITOS,RESTO DE LOS DELITOS (OTROS),RESTO DE LOS DELITOS (OTROS),195,182,208,215,249,309,219,229,239,287,224,245

In [90]:
columnas_df1 = df1.columns
columnas_df1

Index(['Año', 'Clave_Ent', 'Entidad', 'Bien jurídico afectado',
       'Tipo de delito', 'Subtipo de delito', 'Modalidad', 'Enero', 'Febrero',
       'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre',
       'Octubre', 'Noviembre', 'Diciembre'],
      dtype='object')

In [115]:
columnas_df2 = df2.columns
columnas_df2

Index(['AÑO', 'ENTIDAD', 'MODALIDAD', 'TIPO', 'SUBTIPO', 'ENERO', 'FEBRERO',
       'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE',
       'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE'],
      dtype='object')

In [92]:
df1 = df1.drop(columns=[columnas_df1[1]])
columnas_df1 = df1.columns
columnas_df1

Index(['Año', 'Entidad', 'Bien jurídico afectado', 'Tipo de delito',
       'Subtipo de delito', 'Modalidad', 'Enero', 'Febrero', 'Marzo', 'Abril',
       'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre',
       'Noviembre', 'Diciembre'],
      dtype='object')

In [93]:
selected_columns = [columnas_df1[2], columnas_df1[3], columnas_df1[4], columnas_df1[5]]
combinaciones_df1 = df1[selected_columns].drop_duplicates()
combinaciones_df1

,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad
0,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego
1,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca
2,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento
3,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado
4,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego
...,...,...,...,...
93,Otros bienes jurídicos afectados (del fuero co...,Falsificación,Falsificación,Falsificación
94,Otros bienes jurídicos afectados (del fuero co...,Contra el medio ambiente,Contra el medio ambiente,Contra el medio ambiente
95,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos
96,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales
97,Otros bienes jurídicos afectados (del fuero co...,Otros delitos del Fuero Común,Otros delitos del Fuero Común,Otros delitos del Fuero Común

In [94]:
lines_to_remove = [22, 32, 33, 34, 35, 36, 37, 38, 75, 76, 77, 80, 81, 82, 83, 84, 89, 91, 92, 93, 94, 95, 96, 97]
combinaciones_df1 = combinaciones_df1.drop(index=lines_to_remove)
combinaciones_df1

,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad
0,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego
1,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca
2,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento
3,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado
4,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego
...,...,...,...,...
85,La sociedad,Corrupción de menores,Corrupción de menores,Corrupción de menores
86,La sociedad,Trata de personas,Trata de personas,Trata de personas
87,La sociedad,Otros delitos contra la sociedad,Otros delitos contra la sociedad,Otros delitos contra la sociedad
88,Otros bienes jurídicos afectados (del fuero co...,Narcomenudeo,Narcomenudeo,Narcomenudeo
90,Otros bienes jurídicos afectados (del fuero co...,Allanamiento de morada,Allanamiento de morada,Allanamiento de morada

In [95]:
df1_delitos_selec = df1.merge(combinaciones_df1,
                              on=selected_columns,
                              how='inner')
df1_delitos_selec

,Año,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2,1,2,2.0,2.0,1.0
1,2015,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0,1,0,0.0,0.0,1.0
2,2015,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0,1,2,0.0,0.0,0.0
3,2015,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2,0,0,1,0,0,0,0,0,0.0,0.0,0.0
4,2015,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23675,2024,Zacatecas,La sociedad,Corrupción de menores,Corrupción de menores,Corrupción de menores,1,4,5,4,0,2,1,0,1,NaN,NaN,NaN
23676,2024,Zacatecas,La sociedad,Trata de personas,Trata de personas,Trata de personas,6,1,1,3,5,5,1,2,2,NaN,NaN,NaN
23677,2024,Zacatecas,La sociedad,Otros delitos contra la sociedad,Otros delitos contra la sociedad,Otros delitos contra la sociedad,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
23678,2024,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Narcomenudeo,Narcomenudeo,Narcomenudeo,15,30,17,30,31,32,43,44,42,NaN,NaN,NaN
23679,2024,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Allanamiento de morada,Allanamiento de morada,Allanamiento de morada,14,11,14,10,18,15,13,16,13,NaN,NaN,NaN

In [96]:
combinaciones_df1_v2 = df1_delitos_selec[selected_columns].drop_duplicates()
combinaciones_df1_v2

,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad
0,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego
1,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca
2,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento
3,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado
4,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego
...,...,...,...,...
69,La sociedad,Corrupción de menores,Corrupción de menores,Corrupción de menores
70,La sociedad,Trata de personas,Trata de personas,Trata de personas
71,La sociedad,Otros delitos contra la sociedad,Otros delitos contra la sociedad,Otros delitos contra la sociedad
72,Otros bienes jurídicos afectados (del fuero co...,Narcomenudeo,Narcomenudeo,Narcomenudeo
73,Otros bienes jurídicos afectados (del fuero co...,Allanamiento de morada,Allanamiento de morada,Allanamiento de morada

In [97]:
df2 = df2.drop(columns=[columnas_df2[1]])
columnas_df2 = df2.columns
columnas_df2

Index(['AÑO', 'ENTIDAD', 'MODALIDAD', 'TIPO', 'SUBTIPO', 'ENERO', 'FEBRERO',
       'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE',
       'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE'],
      dtype='object')

In [98]:
selected_columns2 = [columnas_df2[2], columnas_df2[3], columnas_df2[4]]
combinaciones_df2 = df2[selected_columns2].drop_duplicates()
combinaciones_df2

                MODALIDAD                     TIPO                  SUBTIPO
0   DELITOS PATRIMONIALES       ABUSO DE CONFIANZA       ABUSO DE CONFIANZA
1   DELITOS PATRIMONIALES  DAÑO EN PROPIEDAD AJENA  DAÑO EN PROPIEDAD AJENA
2   DELITOS PATRIMONIALES                EXTORSION                EXTORSION
3   DELITOS PATRIMONIALES                   FRAUDE                   FRAUDE
4   DELITOS PATRIMONIALES                  DESPOJO            CON VIOLENCIA
..                    ...                      ...                      ...
61               LESIONES                  DOLOSAS        CON ARMA DE FUEGO
62               LESIONES                  DOLOSAS                    OTROS
63               LESIONES                  DOLOSAS                SIN DATOS
64               LESIONES                 CULPOSAS          CON ARMA BLANCA
65               LESIONES                 CULPOSAS        CON ARMA DE FUEGO

[66 rows x 3 columns]

In [99]:
lines_to_remove2 = [0, 2, 3, 7, 17, 18, 19, 20]
combinaciones_df2 = combinaciones_df2.drop(index=lines_to_remove2)
combinaciones_df2

,MODALIDAD,TIPO,SUBTIPO
1,DELITOS PATRIMONIALES,DAÑO EN PROPIEDAD AJENA,DAÑO EN PROPIEDAD AJENA
4,DELITOS PATRIMONIALES,DESPOJO,CON VIOLENCIA
5,DELITOS PATRIMONIALES,DESPOJO,SIN VIOLENCIA
6,DELITOS PATRIMONIALES,DESPOJO,SIN DATOS
8,HOMICIDIOS,DOLOSOS,CON ARMA DE FUEGO
9,HOMICIDIOS,DOLOSOS,CON ARMA BLANCA
10,HOMICIDIOS,DOLOSOS,OTROS
11,HOMICIDIOS,DOLOSOS,SIN DATOS
12,HOMICIDIOS,CULPOSOS,CON ARMA DE FUEGO
13,HOMICIDIOS,CULPOSOS,CON ARMA BLANCA
14,HOMICIDIOS,CULPOSOS,OTROS
15,LESIONES,CULPOSAS,OTROS
16,LESIONES,CULPOSAS,SIN DATOS
21,PRIV. DE LA LIBERTAD (SECUESTRO),SECUESTRO,SECUESTRO
22,ROBO COMUN,CON VIOLENCIA,A CASA HABITACION
23,ROBO COMUN,CON VIOLENCIA,A NEGOCIO
24,ROBO COMUN,CON VIOLENCIA,DE VEHICULOS
25,ROBO COMUN,CON VIOLENCIA,A TRANSPORTISTAS
26,ROBO COMUN,CON VIOLENCIA,A TRANSEUNTES
27,ROBO COMUN,CON VIOLENCIA,OTROS
28,ROBO COMUN,CON VIOLENCIA,SIN DATOS
29,ROBO COMUN,SIN VIOLENCIA,A CASA HABITACION
30,ROBO COMUN,SIN VIOLENCIA,A NEGOCIO
31,ROBO COMUN,SIN VIOLENCIA,DE VEHICULOS
32,ROBO COMUN,SIN VIOLENCIA,A TRANSPORTISTAS
33,ROBO COMUN,SIN VIOLENCIA,A TRANSEUNTES
34,ROBO COMUN,SIN VIOLENCIA,OTROS
35,ROBO COMUN,SIN VIOLENCIA,SIN DATOS
36,ROBO DE GANADO (ABIGEATO),ABIGEATO,ABIGEATO
37,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,A BANCOS
38,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,A CASA DE BOLSA
39,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,A CASA DE CAMBIO
40,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,A EMPRESA DE TRASLADO DE VALORES
41,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,OTROS
42,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,SIN DATOS
43,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,A BANCOS
44,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,A CASA DE BOLSA
45,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,A CASA DE CAMBIO
46,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,A EMPRESA DE TRASLADO DE VALORES
47,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,OTROS
48,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,SIN DATOS
49,ROBO EN CARRETERAS,CON VIOLENCIA,A CAMIONES DE CARGA
50,ROBO EN CARRETERAS,CON VIOLENCIA,A AUTOBUSES
51,ROBO EN CARRETERAS,CON VIOLENCIA,A VEHICULOS PARTICULARES
52,ROBO EN CARRETERAS,CON VIOLENCIA,OTROS
53,ROBO EN CARRETERAS,CON VIOLENCIA,SIN DATOS
54,ROBO EN CARRETERAS,SIN VIOLENCIA,A CAMIONES DE CARGA
55,ROBO EN CARRETERAS,SIN VIOLENCIA,A AUTOBUSES
56,ROBO EN CARRETERAS,SIN VIOLENCIA,A VEHICULOS PARTICULARES
57,ROBO EN CARRETERAS,SIN VIOLENCIA,OTROS
58,ROBO EN CARRETERAS,SIN VIOLENCIA,SIN DATOS
59,HOMICIDIOS,CULPOSOS,SIN DATOS
60,LESIONES,DOLOSAS,CON ARMA BLANCA
61,LESIONES,DOLOSAS,CON ARMA DE FUEGO
62,LESIONES,DOLOSAS,OTROS
63,LESIONES,DOLOSAS,SIN DATOS
64,LESIONES,CULPOSAS,CON ARMA BLANCA
65,LESIONES,CULPOSAS,CON ARMA DE FUEGO

In [112]:
df2_delitos_selec = df2.merge(combinaciones_df2,
                              on=selected_columns2,
                              how='inner')
df2_delitos_selec

,AÑO,ENTIDAD,MODALIDAD,TIPO,SUBTIPO,ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE
0,1997,AGUASCALIENTES,DELITOS PATRIMONIALES,DAÑO EN PROPIEDAD AJENA,DAÑO EN PROPIEDAD AJENA,45,45,45,45,45,45,108,40,117,38,73,133
1,1997,AGUASCALIENTES,DELITOS PATRIMONIALES,DESPOJO,CON VIOLENCIA,0,0,0,0,0,0,0,0,0,0,0,0
2,1997,AGUASCALIENTES,DELITOS PATRIMONIALES,DESPOJO,SIN VIOLENCIA,0,0,0,0,0,0,0,0,0,0,0,0
3,1997,AGUASCALIENTES,DELITOS PATRIMONIALES,DESPOJO,SIN DATOS,0,0,0,0,0,0,0,0,0,0,0,0
4,1997,AGUASCALIENTES,HOMICIDIOS,DOLOSOS,CON ARMA DE FUEGO,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33403,2014,ZACATECAS,DELITOS PATRIMONIALES,DAÑO EN PROPIEDAD AJENA,DAÑO EN PROPIEDAD AJENA,99,91,105,101,135,106,100,108,114,117,80,96
33404,2014,ZACATECAS,DELITOS PATRIMONIALES,DESPOJO,CON VIOLENCIA,1,5,3,2,3,1,4,0,4,1,2,1
33405,2014,ZACATECAS,DELITOS PATRIMONIALES,DESPOJO,SIN VIOLENCIA,13,14,27,24,31,19,22,18,19,27,11,19
33406,2014,ZACATECAS,DELITOS PATRIMONIALES,DESPOJO,SIN DATOS,0,0,0,0,0,0,0,0,0,0,0,0
33407,2014,ZACATECAS,PRIV. DE LA LIBERTAD (SECUESTRO),SECUESTRO,SECUESTRO,3,2,2,2,2,0,1,1,2,0,0,1

In [101]:
combinaciones_df2_v2 = df2_delitos_selec[selected_columns2].drop_duplicates()
combinaciones_df2_v2

,MODALIDAD,TIPO,SUBTIPO
0,DELITOS PATRIMONIALES,DAÑO EN PROPIEDAD AJENA,DAÑO EN PROPIEDAD AJENA
1,DELITOS PATRIMONIALES,DESPOJO,CON VIOLENCIA
2,DELITOS PATRIMONIALES,DESPOJO,SIN VIOLENCIA
3,DELITOS PATRIMONIALES,DESPOJO,SIN DATOS
4,HOMICIDIOS,DOLOSOS,CON ARMA DE FUEGO
5,HOMICIDIOS,DOLOSOS,CON ARMA BLANCA
6,HOMICIDIOS,DOLOSOS,OTROS
7,HOMICIDIOS,DOLOSOS,SIN DATOS
8,HOMICIDIOS,CULPOSOS,CON ARMA DE FUEGO
9,HOMICIDIOS,CULPOSOS,CON ARMA BLANCA
10,HOMICIDIOS,CULPOSOS,OTROS
11,LESIONES,CULPOSAS,OTROS
12,LESIONES,CULPOSAS,SIN DATOS
13,PRIV. DE LA LIBERTAD (SECUESTRO),SECUESTRO,SECUESTRO
14,ROBO COMUN,CON VIOLENCIA,A CASA HABITACION
15,ROBO COMUN,CON VIOLENCIA,A NEGOCIO
16,ROBO COMUN,CON VIOLENCIA,DE VEHICULOS
17,ROBO COMUN,CON VIOLENCIA,A TRANSPORTISTAS
18,ROBO COMUN,CON VIOLENCIA,A TRANSEUNTES
19,ROBO COMUN,CON VIOLENCIA,OTROS
20,ROBO COMUN,CON VIOLENCIA,SIN DATOS
21,ROBO COMUN,SIN VIOLENCIA,A CASA HABITACION
22,ROBO COMUN,SIN VIOLENCIA,A NEGOCIO
23,ROBO COMUN,SIN VIOLENCIA,DE VEHICULOS
24,ROBO COMUN,SIN VIOLENCIA,A TRANSPORTISTAS
25,ROBO COMUN,SIN VIOLENCIA,A TRANSEUNTES
26,ROBO COMUN,SIN VIOLENCIA,OTROS
27,ROBO COMUN,SIN VIOLENCIA,SIN DATOS
28,ROBO DE GANADO (ABIGEATO),ABIGEATO,ABIGEATO
29,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,A BANCOS
30,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,A CASA DE BOLSA
31,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,A CASA DE CAMBIO
32,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,A EMPRESA DE TRASLADO DE VALORES
33,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,OTROS
34,ROBO EN INSTITUCIONES BANCARIAS,CON VIOLENCIA,SIN DATOS
35,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,A BANCOS
36,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,A CASA DE BOLSA
37,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,A CASA DE CAMBIO
38,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,A EMPRESA DE TRASLADO DE VALORES
39,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,OTROS
40,ROBO EN INSTITUCIONES BANCARIAS,SIN VIOLENCIA,SIN DATOS
41,ROBO EN CARRETERAS,CON VIOLENCIA,A CAMIONES DE CARGA
42,ROBO EN CARRETERAS,CON VIOLENCIA,A AUTOBUSES
43,ROBO EN CARRETERAS,CON VIOLENCIA,A VEHICULOS PARTICULARES
44,ROBO EN CARRETERAS,CON VIOLENCIA,OTROS
45,ROBO EN CARRETERAS,CON VIOLENCIA,SIN DATOS
46,ROBO EN CARRETERAS,SIN VIOLENCIA,A CAMIONES DE CARGA
47,ROBO EN CARRETERAS,SIN VIOLENCIA,A AUTOBUSES
48,ROBO EN CARRETERAS,SIN VIOLENCIA,A VEHICULOS PARTICULARES
49,ROBO EN CARRETERAS,SIN VIOLENCIA,OTROS
50,ROBO EN CARRETERAS,SIN VIOLENCIA,SIN DATOS
51,HOMICIDIOS,CULPOSOS,SIN DATOS
52,LESIONES,DOLOSAS,CON ARMA BLANCA
53,LESIONES,DOLOSAS,CON ARMA DE FUEGO
54,LESIONES,DOLOSAS,OTROS
55,LESIONES,DOLOSAS,SIN DATOS
56,LESIONES,CULPOSAS,CON ARMA BLANCA
57,LESIONES,CULPOSAS,CON ARMA DE FUEGO

In [102]:
df1_delitos = df1_delitos_selec.drop(columns=[columnas_df1[2], columnas_df1[3], columnas_df1[4], columnas_df1[5]])
df1_delitos.columns = df1_delitos.columns.str.lower()
columnas_df1 = df1_delitos.columns
columnas_df1

Index(['año', 'entidad', 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
       'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
      dtype='object')

In [103]:
id_vars1 = [columnas_df1[0], columnas_df1[1]]
value_vars1 = [columnas_df1[2], columnas_df1[3], columnas_df1[4], columnas_df1[5], columnas_df1[6], columnas_df1[7], columnas_df1[8], columnas_df1[9], columnas_df1[10], columnas_df1[11], columnas_df1[12], columnas_df1[13]]

In [104]:
df1_melted = pd.melt(df1_delitos, id_vars=id_vars1,
                    value_vars=value_vars1,
                    var_name='mes', value_name='eventos').dropna()
df1_melted

         año         entidad        mes  eventos
0       2015  Aguascalientes      enero      3.0
1       2015  Aguascalientes      enero      1.0
2       2015  Aguascalientes      enero      0.0
3       2015  Aguascalientes      enero      2.0
4       2015  Aguascalientes      enero      0.0
...      ...             ...        ...      ...
281787  2023       Zacatecas  diciembre      1.0
281788  2023       Zacatecas  diciembre      1.0
281789  2023       Zacatecas  diciembre      0.0
281790  2023       Zacatecas  diciembre     19.0
281791  2023       Zacatecas  diciembre     13.0

[277056 rows x 4 columns]

In [106]:
df1_final = df1_melted.groupby(['año', 'entidad', 'mes'], as_index=False)['eventos'].sum()
df1_final

       año         entidad         mes  eventos
0     2015  Aguascalientes       abril   1511.0
1     2015  Aguascalientes      agosto   1526.0
2     2015  Aguascalientes   diciembre   1296.0
3     2015  Aguascalientes       enero   1411.0
4     2015  Aguascalientes     febrero   1398.0
...    ...             ...         ...      ...
3739  2024       Zacatecas       julio   1074.0
3740  2024       Zacatecas       junio   1139.0
3741  2024       Zacatecas       marzo   1110.0
3742  2024       Zacatecas        mayo   1272.0
3743  2024       Zacatecas  septiembre   1065.0

[3744 rows x 4 columns]

In [116]:
df2_delitos = df2_delitos_selec.drop(columns=[columnas_df2[2], columnas_df2[3], columnas_df2[4]])
df2_delitos.columns = df2_delitos.columns.str.lower()
columnas_df2 = df2_delitos.columns
columnas_df2

Index(['año', 'entidad', 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
       'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
      dtype='object')

In [117]:
df2_melted = pd.melt(df2_delitos, id_vars=id_vars1,
                    value_vars=value_vars1,
                    var_name='mes', value_name='eventos').dropna()
df2_melted

         año         entidad        mes  eventos
0       1997  AGUASCALIENTES      enero       45
1       1997  AGUASCALIENTES      enero        0
2       1997  AGUASCALIENTES      enero        0
3       1997  AGUASCALIENTES      enero        0
4       1997  AGUASCALIENTES      enero        0
...      ...             ...        ...      ...
400891  2014       ZACATECAS  diciembre       96
400892  2014       ZACATECAS  diciembre        1
400893  2014       ZACATECAS  diciembre       19
400894  2014       ZACATECAS  diciembre        0
400895  2014       ZACATECAS  diciembre        1

[400896 rows x 4 columns]

In [119]:
df2_final = df2_melted.groupby(['año', 'entidad', 'mes'], as_index=False)['eventos'].sum()
df2_final

       año         entidad         mes  eventos
0     1997  AGUASCALIENTES       abril      737
1     1997  AGUASCALIENTES      agosto      502
2     1997  AGUASCALIENTES   diciembre      516
3     1997  AGUASCALIENTES       enero      737
4     1997  AGUASCALIENTES     febrero      737
...    ...             ...         ...      ...
6907  2014       ZACATECAS       marzo      995
6908  2014       ZACATECAS        mayo      941
6909  2014       ZACATECAS   noviembre      882
6910  2014       ZACATECAS     octubre     1070
6911  2014       ZACATECAS  septiembre     1032

[6912 rows x 4 columns]

In [120]:
df1_final['entidad'] = df1_final['entidad'].str.lower()
df2_final['entidad'] = df2_final['entidad'].str.lower()

In [129]:
df1_final['entidad'].unique()

array(['aguascalientes', 'baja california', 'baja california sur',
       'campeche', 'chiapas', 'chihuahua', 'ciudad de méxico',
       'coahuila de zaragoza', 'colima', 'durango', 'guanajuato',
       'guerrero', 'hidalgo', 'jalisco', 'michoacán de ocampo', 'morelos',
       'méxico', 'nayarit', 'nuevo león', 'oaxaca', 'puebla', 'querétaro',
       'quintana roo', 'san luis potosí', 'sinaloa', 'sonora', 'tabasco',
       'tamaulipas', 'tlaxcala', 'veracruz de ignacio de la llave',
       'yucatán', 'zacatecas'], dtype=object)

In [132]:
df2_final['entidad'].unique()

array(['aguascalientes', 'baja california', 'baja california sur',
       'campeche', 'chiapas', 'chihuahua', 'ciudad de mexico', 'coahuila',
       'colima', 'durango', 'guanajuato', 'guerrero', 'hidalgo',
       'jalisco', 'mexico', 'michoacan', 'morelos', 'nayarit',
       'nuevo leon', 'oaxaca', 'puebla', 'queretaro', 'quintana roo',
       'san luis potosi', 'sinaloa', 'sonora', 'tabasco', 'tamaulipas',
       'tlaxcala', 'veracruz', 'yucatan', 'zacatecas'], dtype=object)

In [133]:
df1_final['entidad'].unique() == df2_final['entidad'].unique()

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True, False, False,  True])

In [134]:
replacements = {'ciudad de méxico': 'ciudad de mexico', 
                'coahuila de zaragoza': 'coahuila', 
                'michoacán de ocampo': 'michoacan',
                'méxico': 'mexico',
                'nuevo león': 'nuevo leon',
                'querétaro': 'queretaro',
                'san luis potosí': 'san luis potosi',
                'veracruz de ignacio de la llave': 'veracruz',
                'yucatán': 'yucatan'}

In [135]:
df1_final['entidad'] = df1_final['entidad'].replace(replacements)

In [136]:
sorted(df1_final['entidad'].unique()) == sorted(df2_final['entidad'].unique())

True

In [137]:
df1_final

       año         entidad         mes  eventos
0     2015  aguascalientes       abril   1511.0
1     2015  aguascalientes      agosto   1526.0
2     2015  aguascalientes   diciembre   1296.0
3     2015  aguascalientes       enero   1411.0
4     2015  aguascalientes     febrero   1398.0
...    ...             ...         ...      ...
3739  2024       zacatecas       julio   1074.0
3740  2024       zacatecas       junio   1139.0
3741  2024       zacatecas       marzo   1110.0
3742  2024       zacatecas        mayo   1272.0
3743  2024       zacatecas  septiembre   1065.0

[3744 rows x 4 columns]

In [138]:
df2_final

       año         entidad         mes  eventos
0     1997  aguascalientes       abril      737
1     1997  aguascalientes      agosto      502
2     1997  aguascalientes   diciembre      516
3     1997  aguascalientes       enero      737
4     1997  aguascalientes     febrero      737
...    ...             ...         ...      ...
6907  2014       zacatecas       marzo      995
6908  2014       zacatecas        mayo      941
6909  2014       zacatecas   noviembre      882
6910  2014       zacatecas     octubre     1070
6911  2014       zacatecas  septiembre     1032

[6912 rows x 4 columns]

In [141]:
df_final = pd.concat([df1_final, df2_final], ignore_index=True)
df_final = df_final.sort_values(by=['año', 'entidad', 'mes'], ascending=[True, True, True])
df_final = df_final.reset_index(drop=True)
df_final

        año         entidad         mes  eventos
0      1997  aguascalientes       abril    737.0
1      1997  aguascalientes      agosto    502.0
2      1997  aguascalientes   diciembre    516.0
3      1997  aguascalientes       enero    737.0
4      1997  aguascalientes     febrero    737.0
...     ...             ...         ...      ...
10651  2024       zacatecas       julio   1074.0
10652  2024       zacatecas       junio   1139.0
10653  2024       zacatecas       marzo   1110.0
10654  2024       zacatecas        mayo   1272.0
10655  2024       zacatecas  septiembre   1065.0

[10656 rows x 4 columns]

In [142]:
df_final.to_csv('eventos_violentos.csv', index=False)

In [143]:
combinaciones_df1.to_csv('eventos_considerados>2015.csv', index=False)
combinaciones_df2.to_csv('eventos_considerados<2015.csv', index=False)